export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

/* Startups */
export const LOAD_STARTUPS_SUCCESS = 'LOAD_STARTUPS_SUCCESS';
export const CREATE_STARTUP_SUCCESS = 'CREATE_STARTUP_SUCCESS';
export const UPDATE_STARTUP_SUCCESS = 'UPDATE_STARTUP_SUCCESS';
export const LOAD_INDUSTRIES_SUCCESS = 'LOAD_INDUSTRIES_SUCCESS';

/* Blog */

export const FETCH_POSTS = 'FETCH_POSTS';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';

export const FETCH_POST = 'FETCH_POST';
export const FETCH_POST_SUCCESS = 'FETCH_POST_SUCCESS';
export const FETCH_POST_FAILURE = 'FETCH_POST_FAILURE';

export const DELETE_POST = 'DELETE_POST';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_FAILURE = 'DELETE_POST_FAILURE';



